# Generated by Django 4.2.28 on 2026-02-28 19:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('XMR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text Message'), ('SYSTEM', 'System Message'), ('JOIN', 'User Joined'), ('LEAVE', 'User Left'), ('INVESTMENT', 'Investment Update'), ('PAYOUT', 'Payout Notification'), ('ALERT', 'Alert'), ('IMAGE', 'Image'), ('FILE', 'File')], db_index=True, default='TEXT', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat/images/%Y/%m/%d/')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat/files/%Y/%m/%d/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_announcement', models.BooleanField(default=False)),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='XMR.investment')),
                ('mentions', models.ManyToManyField(blank=True, related_name='mentioned_in_messages', to=settings.AUTH_USER_MODEL)),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_messages', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='XMR.chatmessage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dm_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('last_message', models.TextField(blank=True, max_length=200)),
                ('last_message_time', models.DateTimeField(auto_now=True)),
                ('user1_unread', models.IntegerField(default=0)),
                ('user2_unread', models.IntegerField(default=0)),
                ('user1_blocked', models.BooleanField(default=False)),
                ('user2_blocked', models.BooleanField(default=False)),
                ('user1_muted', models.BooleanField(default=False)),
                ('user2_muted', models.BooleanField(default=False)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_initiated', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_time'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('room_type', models.CharField(choices=[('PUBLIC', 'Public Room'), ('PRIVATE', 'Private Room'), ('DIRECT', 'Direct Message'), ('INVESTMENT', 'Investment Discussion'), ('SUPPORT', 'Support Chat')], db_index=True, default='PUBLIC', max_length=20)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_protected', models.BooleanField(default=False, help_text='Requires approval to join')),
                ('max_participants', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(1000)])),
                ('password', models.CharField(blank=True, help_text='Optional password for protected rooms', max_length=128, null=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome or emoji icon', max_length=50)),
                ('color', models.CharField(default='primary', max_length=20)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('total_messages', models.IntegerField(default=0, editable=False)),
                ('online_count', models.IntegerField(default=0, editable=False)),
                ('banned_users', models.ManyToManyField(blank=True, related_name='banned_from_rooms', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chat_rooms', to=settings.AUTH_USER_MODEL)),
                ('moderators', models.ManyToManyField(blank=True, related_name='moderated_rooms', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='chat_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Room',
                'verbose_name_plural': 'Chat Rooms',
                'ordering': ['-last_activity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChatReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('👍', 'Thumbs Up'), ('❤️', 'Heart'), ('😂', 'Laughing'), ('😮', 'Wow'), ('😢', 'Sad'), ('👏', 'Applause'), ('🎉', 'Celebration'), ('🔥', 'Fire'), ('💯', '100'), ('❓', 'Question')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='XMR.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_enabled', models.BooleanField(default=True)),
                ('desktop_notifications', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=False)),
                ('room_settings', models.JSONField(blank=True, default=dict, help_text="Format: {'room_id': {'mute': bool, 'notification_type': 'ALL/MENTIONS/NONE'}}")),
                ('dnd_enabled', models.BooleanField(default=False)),
                ('dnd_start', models.TimeField(blank=True, null=True)),
                ('dnd_end', models.TimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Notification Setting',
                'verbose_name_plural': 'Chat Notification Settings',
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='XMR.chatroom'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='XMR.transaction'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChatActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('JOINED', 'Joined Room'), ('LEFT', 'Left Room'), ('BAN', 'User Banned'), ('UNBAN', 'User Unbanned'), ('MOD_ADD', 'Moderator Added'), ('MOD_REMOVE', 'Moderator Removed'), ('KICK', 'User Kicked'), ('MUTE', 'User Muted'), ('UNMUTE', 'User Unmuted'), ('PIN', 'Message Pinned'), ('UNPIN', 'Message Unpinned'), ('CLEAR', 'Chat Cleared')], db_index=True, max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='XMR.chatmessage')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='XMR.chatroom')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectMessageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('dm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='XMR.directmessage')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_dms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['dm', '-created_at'], name='XMR_directm_dm_id_ddbefb_idx'), models.Index(fields=['sender', '-created_at'], name='XMR_directm_sender__a8561a_idx'), models.Index(fields=['is_read', 'dm'], name='XMR_directm_is_read_151547_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['user1', '-last_message_time'], name='XMR_directm_user1_i_5986b5_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['user2', '-last_message_time'], name='XMR_directm_user2_i_f801f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='directmessage',
            unique_together={('user1', 'user2')},
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['slug'], name='XMR_chatroo_slug_bd94cc_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['room_type', 'is_active'], name='XMR_chatroo_room_ty_789fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['-last_activity'], name='XMR_chatroo_last_ac_018854_idx'),
        ),
        migrations.AddIndex(
            model_name='chatreaction',
            index=models.Index(fields=['message', 'reaction'], name='XMR_chatrea_message_93f698_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatreaction',
            unique_together={('message', 'user', 'reaction')},
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', '-created_at'], name='XMR_chatmes_room_id_2dcd9e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['user', '-created_at'], name='XMR_chatmes_user_id_bbf753_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['message_type', 'created_at'], name='XMR_chatmes_message_99c677_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_pinned', 'room'], name='XMR_chatmes_is_pinn_74eeeb_idx'),
        ),
        migrations.AddIndex(
            model_name='chatactivity',
            index=models.Index(fields=['room', '-created_at'], name='XMR_chatact_room_id_30dfe8_idx'),
        ),
        migrations.AddIndex(
            model_name='chatactivity',
            index=models.Index(fields=['user', '-created_at'], name='XMR_chatact_user_id_c991b5_idx'),
        ),
        migrations.AddIndex(
            model_name='chatactivity',
            index=models.Index(fields=['action', '-created_at'], name='XMR_chatact_action_3868a9_idx'),
        ),
    ]
