# Generated by Django 4.2.28 on 2026-03-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XMR', '0002_chatmessage_directmessage_chatroom_chatreaction_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='XMR_userpro_referra_8ed72e_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='XMR_userpro_phone_n_df7076_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='XMR_userpro_created_5cf7f6_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='away_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='chat_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='chat_sounds',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['online_status', 'last_seen'], name='XMR_userpro_online__e5acc0_idx'),
        ),
    ]
