# Generated by Django 4.2.28 on 2026-03-01 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('XMR', '0003_remove_userprofile_xmr_userpro_referra_8ed72e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatNotificationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('INVITE', 'Room Invite'), ('JOIN', 'User Joined'), ('LEAVE', 'User Left'), ('BAN', 'User Banned'), ('UNBAN', 'User Unbanned'), ('MOD_ADD', 'Moderator Added'), ('MOD_REMOVE', 'Moderator Removed'), ('EVENT', 'Room Event'), ('ANNOUNCEMENT', 'Announcement'), ('ROOM_DELETED', 'Room Deleted')], db_index=True, max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read', '-created_at'], name='XMR_chatnot_user_id_29537e_idx'), models.Index(fields=['notification_type', '-created_at'], name='XMR_chatnot_notific_51f79b_idx')],
            },
        ),
    ]
