# Generated by Django 4.2.30 on 2026-08-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XMR', '0005_alter_chatnotificationmessage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='return_days',
            field=models.IntegerField(default=12, help_text='Number of business days returns are paid'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['referral_code'], name='XMR_userpro_referra_8ed72e_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['phone_number'], name='XMR_userpro_phone_n_df7076_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-created_at'], name='XMR_userpro_created_5cf7f6_idx'),
        ),
    ]
